//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP//
// Created by echo on 2024/12/14.

#ifndef MY_CPP_STL_BY_CLION_FINCTIONAL_CPP
#define MY_CPP_STL_BY_CLION_FINCTIONAL_CPP

#endif //MY_CPP_STL_BY_CLION_FINCTIONAL_CPP